/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Defaults from './model/Defaults';
import Defaults1 from './model/Defaults1';
import Description from './model/Description';
import Email from './model/Email';
import Email1 from './model/Email1';
import Email2 from './model/Email2';
import FieldTypeEnum from './model/FieldTypeEnum';
import Fields from './model/Fields';
import Fields1 from './model/Fields1';
import Fields2 from './model/Fields2';
import Htpasswd from './model/Htpasswd';
import LoginCredential from './model/LoginCredential';
import Name from './model/Name';
import Password from './model/Password';
import PodCreateRequest from './model/PodCreateRequest';
import PodCreateResponse from './model/PodCreateResponse';
import PodCreateResponsePod from './model/PodCreateResponsePod';
import PodDeleteResponse from './model/PodDeleteResponse';
import PodGetResponse from './model/PodGetResponse';
import PodId from './model/PodId';
import PodListResponse from './model/PodListResponse';
import PodModel from './model/PodModel';
import PodStatusEnum from './model/PodStatusEnum';
import PodUpdateRequest from './model/PodUpdateRequest';
import PodUpdateRequestTargetStatus from './model/PodUpdateRequestTargetStatus';
import PodUpdateResponse from './model/PodUpdateResponse';
import Quota from './model/Quota';
import QuotaModel from './model/QuotaModel';
import ResourceStatusEnum from './model/ResourceStatusEnum';
import Role from './model/Role';
import Status from './model/Status';
import TemplateCreateRequest from './model/TemplateCreateRequest';
import TemplateCreateResponse from './model/TemplateCreateResponse';
import TemplateCreateResponseTemplate from './model/TemplateCreateResponseTemplate';
import TemplateDeleteResponse from './model/TemplateDeleteResponse';
import TemplateGetResponse from './model/TemplateGetResponse';
import TemplateListResponse from './model/TemplateListResponse';
import TemplateModel from './model/TemplateModel';
import TemplateUpdateRequest from './model/TemplateUpdateRequest';
import TemplateUpdateResponse from './model/TemplateUpdateResponse';
import TimeoutS from './model/TimeoutS';
import TokenResponse from './model/TokenResponse';
import UserCreateRequest from './model/UserCreateRequest';
import UserCreateResponse from './model/UserCreateResponse';
import UserCreateResponseUser from './model/UserCreateResponseUser';
import UserDeleteResponse from './model/UserDeleteResponse';
import UserGetResponse from './model/UserGetResponse';
import UserListResponse from './model/UserListResponse';
import UserModel from './model/UserModel';
import UserModelQuota from './model/UserModelQuota';
import UserRoleEnum from './model/UserRoleEnum';
import UserStatusEnum from './model/UserStatusEnum';
import UserUpdateRequest from './model/UserUpdateRequest';
import UserUpdateResponse from './model/UserUpdateResponse';
import Username from './model/Username';
import Uuid from './model/Uuid';
import Values from './model/Values';
import AdminPodApi from './api/AdminPodApi';
import AdminTemplateApi from './api/AdminTemplateApi';
import AdminUserApi from './api/AdminUserApi';
import AuthApi from './api/AuthApi';
import AuthBpApi from './api/AuthBpApi';
import DefaultApi from './api/DefaultApi';
import HeartbeatApi from './api/HeartbeatApi';
import NonadminPodApi from './api/NonadminPodApi';
import NonadminTemplateApi from './api/NonadminTemplateApi';
import NonadminUserApi from './api/NonadminUserApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Api = require('index'); // See note below*.
* var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Defaults model constructor.
     * @property {module:model/Defaults}
     */
    Defaults,

    /**
     * The Defaults1 model constructor.
     * @property {module:model/Defaults1}
     */
    Defaults1,

    /**
     * The Description model constructor.
     * @property {module:model/Description}
     */
    Description,

    /**
     * The Email model constructor.
     * @property {module:model/Email}
     */
    Email,

    /**
     * The Email1 model constructor.
     * @property {module:model/Email1}
     */
    Email1,

    /**
     * The Email2 model constructor.
     * @property {module:model/Email2}
     */
    Email2,

    /**
     * The FieldTypeEnum model constructor.
     * @property {module:model/FieldTypeEnum}
     */
    FieldTypeEnum,

    /**
     * The Fields model constructor.
     * @property {module:model/Fields}
     */
    Fields,

    /**
     * The Fields1 model constructor.
     * @property {module:model/Fields1}
     */
    Fields1,

    /**
     * The Fields2 model constructor.
     * @property {module:model/Fields2}
     */
    Fields2,

    /**
     * The Htpasswd model constructor.
     * @property {module:model/Htpasswd}
     */
    Htpasswd,

    /**
     * The LoginCredential model constructor.
     * @property {module:model/LoginCredential}
     */
    LoginCredential,

    /**
     * The Name model constructor.
     * @property {module:model/Name}
     */
    Name,

    /**
     * The Password model constructor.
     * @property {module:model/Password}
     */
    Password,

    /**
     * The PodCreateRequest model constructor.
     * @property {module:model/PodCreateRequest}
     */
    PodCreateRequest,

    /**
     * The PodCreateResponse model constructor.
     * @property {module:model/PodCreateResponse}
     */
    PodCreateResponse,

    /**
     * The PodCreateResponsePod model constructor.
     * @property {module:model/PodCreateResponsePod}
     */
    PodCreateResponsePod,

    /**
     * The PodDeleteResponse model constructor.
     * @property {module:model/PodDeleteResponse}
     */
    PodDeleteResponse,

    /**
     * The PodGetResponse model constructor.
     * @property {module:model/PodGetResponse}
     */
    PodGetResponse,

    /**
     * The PodId model constructor.
     * @property {module:model/PodId}
     */
    PodId,

    /**
     * The PodListResponse model constructor.
     * @property {module:model/PodListResponse}
     */
    PodListResponse,

    /**
     * The PodModel model constructor.
     * @property {module:model/PodModel}
     */
    PodModel,

    /**
     * The PodStatusEnum model constructor.
     * @property {module:model/PodStatusEnum}
     */
    PodStatusEnum,

    /**
     * The PodUpdateRequest model constructor.
     * @property {module:model/PodUpdateRequest}
     */
    PodUpdateRequest,

    /**
     * The PodUpdateRequestTargetStatus model constructor.
     * @property {module:model/PodUpdateRequestTargetStatus}
     */
    PodUpdateRequestTargetStatus,

    /**
     * The PodUpdateResponse model constructor.
     * @property {module:model/PodUpdateResponse}
     */
    PodUpdateResponse,

    /**
     * The Quota model constructor.
     * @property {module:model/Quota}
     */
    Quota,

    /**
     * The QuotaModel model constructor.
     * @property {module:model/QuotaModel}
     */
    QuotaModel,

    /**
     * The ResourceStatusEnum model constructor.
     * @property {module:model/ResourceStatusEnum}
     */
    ResourceStatusEnum,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The Status model constructor.
     * @property {module:model/Status}
     */
    Status,

    /**
     * The TemplateCreateRequest model constructor.
     * @property {module:model/TemplateCreateRequest}
     */
    TemplateCreateRequest,

    /**
     * The TemplateCreateResponse model constructor.
     * @property {module:model/TemplateCreateResponse}
     */
    TemplateCreateResponse,

    /**
     * The TemplateCreateResponseTemplate model constructor.
     * @property {module:model/TemplateCreateResponseTemplate}
     */
    TemplateCreateResponseTemplate,

    /**
     * The TemplateDeleteResponse model constructor.
     * @property {module:model/TemplateDeleteResponse}
     */
    TemplateDeleteResponse,

    /**
     * The TemplateGetResponse model constructor.
     * @property {module:model/TemplateGetResponse}
     */
    TemplateGetResponse,

    /**
     * The TemplateListResponse model constructor.
     * @property {module:model/TemplateListResponse}
     */
    TemplateListResponse,

    /**
     * The TemplateModel model constructor.
     * @property {module:model/TemplateModel}
     */
    TemplateModel,

    /**
     * The TemplateUpdateRequest model constructor.
     * @property {module:model/TemplateUpdateRequest}
     */
    TemplateUpdateRequest,

    /**
     * The TemplateUpdateResponse model constructor.
     * @property {module:model/TemplateUpdateResponse}
     */
    TemplateUpdateResponse,

    /**
     * The TimeoutS model constructor.
     * @property {module:model/TimeoutS}
     */
    TimeoutS,

    /**
     * The TokenResponse model constructor.
     * @property {module:model/TokenResponse}
     */
    TokenResponse,

    /**
     * The UserCreateRequest model constructor.
     * @property {module:model/UserCreateRequest}
     */
    UserCreateRequest,

    /**
     * The UserCreateResponse model constructor.
     * @property {module:model/UserCreateResponse}
     */
    UserCreateResponse,

    /**
     * The UserCreateResponseUser model constructor.
     * @property {module:model/UserCreateResponseUser}
     */
    UserCreateResponseUser,

    /**
     * The UserDeleteResponse model constructor.
     * @property {module:model/UserDeleteResponse}
     */
    UserDeleteResponse,

    /**
     * The UserGetResponse model constructor.
     * @property {module:model/UserGetResponse}
     */
    UserGetResponse,

    /**
     * The UserListResponse model constructor.
     * @property {module:model/UserListResponse}
     */
    UserListResponse,

    /**
     * The UserModel model constructor.
     * @property {module:model/UserModel}
     */
    UserModel,

    /**
     * The UserModelQuota model constructor.
     * @property {module:model/UserModelQuota}
     */
    UserModelQuota,

    /**
     * The UserRoleEnum model constructor.
     * @property {module:model/UserRoleEnum}
     */
    UserRoleEnum,

    /**
     * The UserStatusEnum model constructor.
     * @property {module:model/UserStatusEnum}
     */
    UserStatusEnum,

    /**
     * The UserUpdateRequest model constructor.
     * @property {module:model/UserUpdateRequest}
     */
    UserUpdateRequest,

    /**
     * The UserUpdateResponse model constructor.
     * @property {module:model/UserUpdateResponse}
     */
    UserUpdateResponse,

    /**
     * The Username model constructor.
     * @property {module:model/Username}
     */
    Username,

    /**
     * The Uuid model constructor.
     * @property {module:model/Uuid}
     */
    Uuid,

    /**
     * The Values model constructor.
     * @property {module:model/Values}
     */
    Values,

    /**
    * The AdminPodApi service constructor.
    * @property {module:api/AdminPodApi}
    */
    AdminPodApi,

    /**
    * The AdminTemplateApi service constructor.
    * @property {module:api/AdminTemplateApi}
    */
    AdminTemplateApi,

    /**
    * The AdminUserApi service constructor.
    * @property {module:api/AdminUserApi}
    */
    AdminUserApi,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The AuthBpApi service constructor.
    * @property {module:api/AuthBpApi}
    */
    AuthBpApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The HeartbeatApi service constructor.
    * @property {module:api/HeartbeatApi}
    */
    HeartbeatApi,

    /**
    * The NonadminPodApi service constructor.
    * @property {module:api/NonadminPodApi}
    */
    NonadminPodApi,

    /**
    * The NonadminTemplateApi service constructor.
    * @property {module:api/NonadminTemplateApi}
    */
    NonadminTemplateApi,

    /**
    * The NonadminUserApi service constructor.
    * @property {module:api/NonadminUserApi}
    */
    NonadminUserApi
};
