# Use root/example as user/password credentials
version: '3.1'
services:
  authproxy-frontend:
    image: davidliyutong/clpl-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      CLPL_BACKEND_URL: "http://clpl-apiserver:8080"