/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PodCreateRequest from '../model/PodCreateRequest';
import PodCreateResponse from '../model/PodCreateResponse';
import PodDeleteResponse from '../model/PodDeleteResponse';
import PodGetResponse from '../model/PodGetResponse';
import PodListResponse from '../model/PodListResponse';
import PodUpdateRequest from '../model/PodUpdateRequest';
import PodUpdateResponse from '../model/PodUpdateResponse';

/**
* AdminPod service.
* @module api/AdminPodApi
* @version 1.0.0
*/
export default class AdminPodApi {

    /**
    * Constructs a new AdminPodApi. 
    * @alias module:api/AdminPodApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteadminPodAdminPodDelete operation.
     * @callback module:api/AdminPodApi~deleteadminPodAdminPodDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PodDeleteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a pod. This will mark the pod as deleted.
     * @param {String} podId 
     * @param {module:api/AdminPodApi~deleteadminPodAdminPodDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PodDeleteResponse}
     */
    deleteadminPodAdminPodDelete(podId, callback) {
      let postBody = null;
      // verify the required parameter 'podId' is set
      if (podId === undefined || podId === null) {
        throw new Error("Missing the required parameter 'podId' when calling deleteadminPodAdminPodDelete");
      }

      let pathParams = {
        'pod_id': podId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PodDeleteResponse;
      return this.apiClient.callApi(
        '/v1/admin/pods/{pod_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getadminPodAdminPodGet operation.
     * @callback module:api/AdminPodApi~getadminPodAdminPodGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PodGetResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a pod.
     * @param {String} podId 
     * @param {module:api/AdminPodApi~getadminPodAdminPodGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PodGetResponse}
     */
    getadminPodAdminPodGet(podId, callback) {
      let postBody = null;
      // verify the required parameter 'podId' is set
      if (podId === undefined || podId === null) {
        throw new Error("Missing the required parameter 'podId' when calling getadminPodAdminPodGet");
      }

      let pathParams = {
        'pod_id': podId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PodGetResponse;
      return this.apiClient.callApi(
        '/v1/admin/pods/{pod_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getadminPodAdminPodList operation.
     * @callback module:api/AdminPodApi~getadminPodAdminPodListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PodListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all pods.
     * @param {Object} opts Optional parameters
     * @param {Number} [indexStart] 
     * @param {Number} [indexEnd] 
     * @param {String} [extraQueryFilter] 
     * @param {module:api/AdminPodApi~getadminPodAdminPodListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PodListResponse}
     */
    getadminPodAdminPodList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'index_start': opts['indexStart'],
        'index_end': opts['indexEnd'],
        'extra_query_filter': opts['extraQueryFilter']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PodListResponse;
      return this.apiClient.callApi(
        '/v1/admin/pods', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postadminPodAdminPodCreate operation.
     * @callback module:api/AdminPodApi~postadminPodAdminPodCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PodCreateResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a pod.
     * @param {Object} opts Optional parameters
     * @param {module:model/PodCreateRequest} [podCreateRequest] 
     * @param {module:api/AdminPodApi~postadminPodAdminPodCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PodCreateResponse}
     */
    postadminPodAdminPodCreate(opts, callback) {
      opts = opts || {};
      let postBody = opts['podCreateRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PodCreateResponse;
      return this.apiClient.callApi(
        '/v1/admin/pods', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putadminPodAdminPodUpdate operation.
     * @callback module:api/AdminPodApi~putadminPodAdminPodUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PodUpdateResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a pod.
     * @param {String} podId 
     * @param {Object} opts Optional parameters
     * @param {module:model/PodUpdateRequest} [podUpdateRequest] 
     * @param {module:api/AdminPodApi~putadminPodAdminPodUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PodUpdateResponse}
     */
    putadminPodAdminPodUpdate(podId, opts, callback) {
      opts = opts || {};
      let postBody = opts['podUpdateRequest'];
      // verify the required parameter 'podId' is set
      if (podId === undefined || podId === null) {
        throw new Error("Missing the required parameter 'podId' when calling putadminPodAdminPodUpdate");
      }

      let pathParams = {
        'pod_id': podId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PodUpdateResponse;
      return this.apiClient.callApi(
        '/v1/admin/pods/{pod_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
