/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TemplateCreateRequest from '../model/TemplateCreateRequest';
import TemplateCreateResponse from '../model/TemplateCreateResponse';
import TemplateDeleteResponse from '../model/TemplateDeleteResponse';
import TemplateGetResponse from '../model/TemplateGetResponse';
import TemplateListResponse from '../model/TemplateListResponse';
import TemplateUpdateRequest from '../model/TemplateUpdateRequest';
import TemplateUpdateResponse from '../model/TemplateUpdateResponse';

/**
* AdminTemplate service.
* @module api/AdminTemplateApi
* @version 1.0.0
*/
export default class AdminTemplateApi {

    /**
    * Constructs a new AdminTemplateApi. 
    * @alias module:api/AdminTemplateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteadminTemplateAdminTemplateDelete operation.
     * @callback module:api/AdminTemplateApi~deleteadminTemplateAdminTemplateDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TemplateDeleteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a template. This will mark the pod as deleted.
     * @param {String} templateId 
     * @param {module:api/AdminTemplateApi~deleteadminTemplateAdminTemplateDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TemplateDeleteResponse}
     */
    deleteadminTemplateAdminTemplateDelete(templateId, callback) {
      let postBody = null;
      // verify the required parameter 'templateId' is set
      if (templateId === undefined || templateId === null) {
        throw new Error("Missing the required parameter 'templateId' when calling deleteadminTemplateAdminTemplateDelete");
      }

      let pathParams = {
        'template_id': templateId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TemplateDeleteResponse;
      return this.apiClient.callApi(
        '/v1/admin/templates/{template_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getadminTemplateAdminTemplateGet operation.
     * @callback module:api/AdminTemplateApi~getadminTemplateAdminTemplateGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TemplateGetResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a template.
     * @param {String} templateId 
     * @param {module:api/AdminTemplateApi~getadminTemplateAdminTemplateGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TemplateGetResponse}
     */
    getadminTemplateAdminTemplateGet(templateId, callback) {
      let postBody = null;
      // verify the required parameter 'templateId' is set
      if (templateId === undefined || templateId === null) {
        throw new Error("Missing the required parameter 'templateId' when calling getadminTemplateAdminTemplateGet");
      }

      let pathParams = {
        'template_id': templateId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TemplateGetResponse;
      return this.apiClient.callApi(
        '/v1/admin/templates/{template_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getadminTemplateAdminTemplateList operation.
     * @callback module:api/AdminTemplateApi~getadminTemplateAdminTemplateListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TemplateListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all templates.
     * @param {Object} opts Optional parameters
     * @param {Number} [indexStart] 
     * @param {Number} [indexEnd] 
     * @param {String} [extraQueryFilter] 
     * @param {module:api/AdminTemplateApi~getadminTemplateAdminTemplateListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TemplateListResponse}
     */
    getadminTemplateAdminTemplateList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'index_start': opts['indexStart'],
        'index_end': opts['indexEnd'],
        'extra_query_filter': opts['extraQueryFilter']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TemplateListResponse;
      return this.apiClient.callApi(
        '/v1/admin/templates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postadminTemplateAdminTemplateCreate operation.
     * @callback module:api/AdminTemplateApi~postadminTemplateAdminTemplateCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TemplateCreateResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a template.
     * @param {Object} opts Optional parameters
     * @param {module:model/TemplateCreateRequest} [templateCreateRequest] 
     * @param {module:api/AdminTemplateApi~postadminTemplateAdminTemplateCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TemplateCreateResponse}
     */
    postadminTemplateAdminTemplateCreate(opts, callback) {
      opts = opts || {};
      let postBody = opts['templateCreateRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TemplateCreateResponse;
      return this.apiClient.callApi(
        '/v1/admin/templates', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putadminTemplateAdminTemplateUpdate operation.
     * @callback module:api/AdminTemplateApi~putadminTemplateAdminTemplateUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TemplateUpdateResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a template.
     * @param {String} templateId 
     * @param {Object} opts Optional parameters
     * @param {module:model/TemplateUpdateRequest} [templateUpdateRequest] 
     * @param {module:api/AdminTemplateApi~putadminTemplateAdminTemplateUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TemplateUpdateResponse}
     */
    putadminTemplateAdminTemplateUpdate(templateId, opts, callback) {
      opts = opts || {};
      let postBody = opts['templateUpdateRequest'];
      // verify the required parameter 'templateId' is set
      if (templateId === undefined || templateId === null) {
        throw new Error("Missing the required parameter 'templateId' when calling putadminTemplateAdminTemplateUpdate");
      }

      let pathParams = {
        'template_id': templateId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TemplateUpdateResponse;
      return this.apiClient.callApi(
        '/v1/admin/templates/{template_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
