/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* AuthBp service.
* @module api/AuthBpApi
* @version 1.0.0
*/
export default class AuthBpApi {

    /**
    * Constructs a new AuthBpApi. 
    * @alias module:api/AuthBpApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getauthBpRetrieveUserEndpoint operation.
     * @callback module:api/AuthBpApi~getauthBpRetrieveUserEndpointCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieveuserendpoint
     * @param {module:api/AuthBpApi~getauthBpRetrieveUserEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getauthBpRetrieveUserEndpoint(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/auth/jwt/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getauthBpVerifyEndpoint operation.
     * @callback module:api/AuthBpApi~getauthBpVerifyEndpointCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Verifyendpoint
     * @param {module:api/AuthBpApi~getauthBpVerifyEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getauthBpVerifyEndpoint(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/auth/jwt/verify', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postauthBpAuthenticateEndpoint operation.
     * @callback module:api/AuthBpApi~postauthBpAuthenticateEndpointCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Authenticateendpoint
     * @param {module:api/AuthBpApi~postauthBpAuthenticateEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postauthBpAuthenticateEndpoint(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/auth/jwt/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postauthBpRefreshEndpoint operation.
     * @callback module:api/AuthBpApi~postauthBpRefreshEndpointCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Refreshendpoint
     * @param {module:api/AuthBpApi~postauthBpRefreshEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postauthBpRefreshEndpoint(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/auth/jwt/refresh', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
