/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OIDCStatusResponse1 from '../model/OIDCStatusResponse1';

/**
* AuthOidc service.
* @module api/AuthOidcApi
* @version 1.0.0
*/
export default class AuthOidcApi {

    /**
    * Constructs a new AuthOidcApi. 
    * @alias module:api/AuthOidcApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getauthOidcAuthorize operation.
     * @callback module:api/AuthOidcApi~getauthOidcAuthorizeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This endpoint is called by identity provider after user login, will redirect to frontend login page with token
     * @param {module:api/AuthOidcApi~getauthOidcAuthorizeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getauthOidcAuthorize(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/auth/oidc/authorize', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getauthOidcLogin operation.
     * @callback module:api/AuthOidcApi~getauthOidcLoginCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This handler redirect user to IdP login page
     * @param {module:api/AuthOidcApi~getauthOidcLoginCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getauthOidcLogin(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/auth/oidc/login', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getauthOidcStatus operation.
     * @callback module:api/AuthOidcApi~getauthOidcStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OIDCStatusResponse1} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Status
     * @param {module:api/AuthOidcApi~getauthOidcStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OIDCStatusResponse1}
     */
    getauthOidcStatus(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OIDCStatusResponse1;
      return this.apiClient.callApi(
        '/v1/auth/oidc/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
