/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Heartbeat service.
* @module api/HeartbeatApi
* @version 1.0.0
*/
export default class HeartbeatApi {

    /**
    * Constructs a new HeartbeatApi. 
    * @alias module:api/HeartbeatApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getheartbeatHeartbeatUser operation.
     * @callback module:api/HeartbeatApi~getheartbeatHeartbeatUserCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * partial(func, *args, **keywords) - new function with partial application
     * of the given arguments and keywords.
     * @param {module:api/HeartbeatApi~getheartbeatHeartbeatUserCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getheartbeatHeartbeatUser(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/heartbeat/user', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
