/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FieldTypeEnum.
* @enum {}
* @readonly
*/
export default class FieldTypeEnum {
    
        /**
         * value: "str"
         * @const
         */
        "str" = "str";

    
        /**
         * value: "int"
         * @const
         */
        "int" = "int";

    
        /**
         * value: "float"
         * @const
         */
        "float" = "float";

    
        /**
         * value: "bool"
         * @const
         */
        "bool" = "bool";

    
        /**
         * value: "datetime"
         * @const
         */
        "datetime" = "datetime";

    
        /**
         * value: "list"
         * @const
         */
        "list" = "list";

    

    /**
    * Returns a <code>FieldTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/FieldTypeEnum} The enum <code>FieldTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

