/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodStatusEnum from './PodStatusEnum';
import ResourceStatusEnum from './ResourceStatusEnum';

/**
 * The PodModel model module.
 * @module model/PodModel
 * @version 1.0.0
 */
class PodModel {
    /**
     * Constructs a new <code>PodModel</code>.
     *      Pod model, used to define pod     
     * @alias module:model/PodModel
     * @param podId {String} 
     * @param name {String} 
     * @param description {String} 
     * @param templateRef {String} 
     * @param cpuLimMCpu {Number} 
     * @param memLimMb {Number} 
     * @param storageLimMb {Number} 
     * @param username {String} 
     * @param createdAt {Date} 
     * @param startedAt {Date} 
     * @param accessedAt {Date} 
     * @param timeoutS {Number} 
     * @param currentStatus {module:model/PodStatusEnum} 
     * @param targetStatus {module:model/PodStatusEnum} 
     */
    constructor(podId, name, description, templateRef, cpuLimMCpu, memLimMb, storageLimMb, username, createdAt, startedAt, accessedAt, timeoutS, currentStatus, targetStatus) { 
        
        PodModel.initialize(this, podId, name, description, templateRef, cpuLimMCpu, memLimMb, storageLimMb, username, createdAt, startedAt, accessedAt, timeoutS, currentStatus, targetStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, podId, name, description, templateRef, cpuLimMCpu, memLimMb, storageLimMb, username, createdAt, startedAt, accessedAt, timeoutS, currentStatus, targetStatus) { 
        obj['pod_id'] = podId;
        obj['name'] = name;
        obj['description'] = description;
        obj['template_ref'] = templateRef;
        obj['cpu_lim_m_cpu'] = cpuLimMCpu;
        obj['mem_lim_mb'] = memLimMb;
        obj['storage_lim_mb'] = storageLimMb;
        obj['username'] = username;
        obj['created_at'] = createdAt;
        obj['started_at'] = startedAt;
        obj['accessed_at'] = accessedAt;
        obj['timeout_s'] = timeoutS;
        obj['current_status'] = currentStatus;
        obj['target_status'] = targetStatus;
    }

    /**
     * Constructs a <code>PodModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodModel} obj Optional instance to populate.
     * @return {module:model/PodModel} The populated <code>PodModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodModel();

            if (data.hasOwnProperty('resource_status')) {
                obj['resource_status'] = ApiClient.convertToType(data['resource_status'], ResourceStatusEnum);
            }
            if (data.hasOwnProperty('pod_id')) {
                obj['pod_id'] = ApiClient.convertToType(data['pod_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('template_ref')) {
                obj['template_ref'] = ApiClient.convertToType(data['template_ref'], 'String');
            }
            if (data.hasOwnProperty('cpu_lim_m_cpu')) {
                obj['cpu_lim_m_cpu'] = ApiClient.convertToType(data['cpu_lim_m_cpu'], 'Number');
            }
            if (data.hasOwnProperty('mem_lim_mb')) {
                obj['mem_lim_mb'] = ApiClient.convertToType(data['mem_lim_mb'], 'Number');
            }
            if (data.hasOwnProperty('storage_lim_mb')) {
                obj['storage_lim_mb'] = ApiClient.convertToType(data['storage_lim_mb'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('accessed_at')) {
                obj['accessed_at'] = ApiClient.convertToType(data['accessed_at'], 'Date');
            }
            if (data.hasOwnProperty('timeout_s')) {
                obj['timeout_s'] = ApiClient.convertToType(data['timeout_s'], 'Number');
            }
            if (data.hasOwnProperty('current_status')) {
                obj['current_status'] = PodStatusEnum.constructFromObject(data['current_status']);
            }
            if (data.hasOwnProperty('target_status')) {
                obj['target_status'] = PodStatusEnum.constructFromObject(data['target_status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodModel.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['pod_id'] && !(typeof data['pod_id'] === 'string' || data['pod_id'] instanceof String)) {
            throw new Error("Expected the field `pod_id` to be a primitive type in the JSON string but got " + data['pod_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['template_ref'] && !(typeof data['template_ref'] === 'string' || data['template_ref'] instanceof String)) {
            throw new Error("Expected the field `template_ref` to be a primitive type in the JSON string but got " + data['template_ref']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

PodModel.RequiredProperties = ["pod_id", "name", "description", "template_ref", "cpu_lim_m_cpu", "mem_lim_mb", "storage_lim_mb", "username", "created_at", "started_at", "accessed_at", "timeout_s", "current_status", "target_status"];

/**
 * @member {module:model/ResourceStatusEnum} resource_status
 */
PodModel.prototype['resource_status'] = undefined;

/**
 * @member {String} pod_id
 */
PodModel.prototype['pod_id'] = undefined;

/**
 * @member {String} name
 */
PodModel.prototype['name'] = undefined;

/**
 * @member {String} description
 */
PodModel.prototype['description'] = undefined;

/**
 * @member {String} template_ref
 */
PodModel.prototype['template_ref'] = undefined;

/**
 * @member {Number} cpu_lim_m_cpu
 */
PodModel.prototype['cpu_lim_m_cpu'] = undefined;

/**
 * @member {Number} mem_lim_mb
 */
PodModel.prototype['mem_lim_mb'] = undefined;

/**
 * @member {Number} storage_lim_mb
 */
PodModel.prototype['storage_lim_mb'] = undefined;

/**
 * @member {String} username
 */
PodModel.prototype['username'] = undefined;

/**
 * @member {Date} created_at
 */
PodModel.prototype['created_at'] = undefined;

/**
 * @member {Date} started_at
 */
PodModel.prototype['started_at'] = undefined;

/**
 * @member {Date} accessed_at
 */
PodModel.prototype['accessed_at'] = undefined;

/**
 * @member {Number} timeout_s
 */
PodModel.prototype['timeout_s'] = undefined;

/**
 * @member {module:model/PodStatusEnum} current_status
 */
PodModel.prototype['current_status'] = undefined;

/**
 * @member {module:model/PodStatusEnum} target_status
 */
PodModel.prototype['target_status'] = undefined;






export default PodModel;

