/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PodStatusEnum.
* @enum {}
* @readonly
*/
export default class PodStatusEnum {
    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "creating"
         * @const
         */
        "creating" = "creating";

    
        /**
         * value: "running"
         * @const
         */
        "running" = "running";

    
        /**
         * value: "stopped"
         * @const
         */
        "stopped" = "stopped";

    
        /**
         * value: "deleting"
         * @const
         */
        "deleting" = "deleting";

    
        /**
         * value: "failed"
         * @const
         */
        "failed" = "failed";

    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    

    /**
    * Returns a <code>PodStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PodStatusEnum} The enum <code>PodStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

