/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodStatusEnum from './PodStatusEnum';

/**
 * The PodUpdateRequest model module.
 * @module model/PodUpdateRequest
 * @version 1.0.0
 */
class PodUpdateRequest {
    /**
     * Constructs a new <code>PodUpdateRequest</code>.
     * Update request for pods, all fields except pod_id are optional. target_status is the target status for the pod to reach. Can be either running or stopped.
     * @alias module:model/PodUpdateRequest
     * @param podId {String} 
     */
    constructor(podId) { 
        
        PodUpdateRequest.initialize(this, podId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, podId) { 
        obj['pod_id'] = podId;
    }

    /**
     * Constructs a <code>PodUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PodUpdateRequest} The populated <code>PodUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodUpdateRequest();

            if (data.hasOwnProperty('cpu_lim_m_cpu')) {
                obj['cpu_lim_m_cpu'] = ApiClient.convertToType(data['cpu_lim_m_cpu'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('force')) {
                obj['force'] = ApiClient.convertToType(data['force'], 'Boolean');
            }
            if (data.hasOwnProperty('gpu')) {
                obj['gpu'] = ApiClient.convertToType(data['gpu'], 'Number');
            }
            if (data.hasOwnProperty('mem_lim_mb')) {
                obj['mem_lim_mb'] = ApiClient.convertToType(data['mem_lim_mb'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pod_id')) {
                obj['pod_id'] = ApiClient.convertToType(data['pod_id'], 'String');
            }
            if (data.hasOwnProperty('storage_lim_mb')) {
                obj['storage_lim_mb'] = ApiClient.convertToType(data['storage_lim_mb'], 'Number');
            }
            if (data.hasOwnProperty('target_status')) {
                obj['target_status'] = ApiClient.convertToType(data['target_status'], PodStatusEnum);
            }
            if (data.hasOwnProperty('template_ref')) {
                obj['template_ref'] = ApiClient.convertToType(data['template_ref'], 'String');
            }
            if (data.hasOwnProperty('timeout_s')) {
                obj['timeout_s'] = ApiClient.convertToType(data['timeout_s'], 'Number');
            }
            if (data.hasOwnProperty('user_uuid')) {
                obj['user_uuid'] = ApiClient.convertToType(data['user_uuid'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodUpdateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['pod_id'] && !(typeof data['pod_id'] === 'string' || data['pod_id'] instanceof String)) {
            throw new Error("Expected the field `pod_id` to be a primitive type in the JSON string but got " + data['pod_id']);
        }
        // ensure the json data is a string
        if (data['template_ref'] && !(typeof data['template_ref'] === 'string' || data['template_ref'] instanceof String)) {
            throw new Error("Expected the field `template_ref` to be a primitive type in the JSON string but got " + data['template_ref']);
        }
        // ensure the json data is a string
        if (data['user_uuid'] && !(typeof data['user_uuid'] === 'string' || data['user_uuid'] instanceof String)) {
            throw new Error("Expected the field `user_uuid` to be a primitive type in the JSON string but got " + data['user_uuid']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

PodUpdateRequest.RequiredProperties = ["pod_id"];

/**
 * @member {Number} cpu_lim_m_cpu
 */
PodUpdateRequest.prototype['cpu_lim_m_cpu'] = undefined;

/**
 * @member {String} description
 */
PodUpdateRequest.prototype['description'] = undefined;

/**
 * @member {Boolean} force
 * @default false
 */
PodUpdateRequest.prototype['force'] = false;

/**
 * @member {Number} gpu
 */
PodUpdateRequest.prototype['gpu'] = undefined;

/**
 * @member {Number} mem_lim_mb
 */
PodUpdateRequest.prototype['mem_lim_mb'] = undefined;

/**
 * @member {String} name
 */
PodUpdateRequest.prototype['name'] = undefined;

/**
 * @member {String} pod_id
 */
PodUpdateRequest.prototype['pod_id'] = undefined;

/**
 * @member {Number} storage_lim_mb
 */
PodUpdateRequest.prototype['storage_lim_mb'] = undefined;

/**
 * @member {module:model/PodStatusEnum} target_status
 */
PodUpdateRequest.prototype['target_status'] = undefined;

/**
 * @member {String} template_ref
 */
PodUpdateRequest.prototype['template_ref'] = undefined;

/**
 * @member {Number} timeout_s
 */
PodUpdateRequest.prototype['timeout_s'] = undefined;

/**
 * @member {String} user_uuid
 */
PodUpdateRequest.prototype['user_uuid'] = undefined;

/**
 * @member {String} username
 */
PodUpdateRequest.prototype['username'] = undefined;






export default PodUpdateRequest;

