/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Defaults1 from './Defaults1';
import Fields1 from './Fields1';

/**
 * The TemplateUpdateRequest model module.
 * @module model/TemplateUpdateRequest
 * @version 1.0.0
 */
class TemplateUpdateRequest {
    /**
     * Constructs a new <code>TemplateUpdateRequest</code>.
     *      Update request for templates, all fields except template_id are optional.     
     * @alias module:model/TemplateUpdateRequest
     * @param templateId {String} 
     */
    constructor(templateId) { 
        
        TemplateUpdateRequest.initialize(this, templateId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, templateId) { 
        obj['template_id'] = templateId;
    }

    /**
     * Constructs a <code>TemplateUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateUpdateRequest} obj Optional instance to populate.
     * @return {module:model/TemplateUpdateRequest} The populated <code>TemplateUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateUpdateRequest();

            if (data.hasOwnProperty('template_id')) {
                obj['template_id'] = ApiClient.convertToType(data['template_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('image_ref')) {
                obj['image_ref'] = ApiClient.convertToType(data['image_ref'], 'String');
            }
            if (data.hasOwnProperty('template_str')) {
                obj['template_str'] = ApiClient.convertToType(data['template_str'], 'String');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = Fields1.constructFromObject(data['fields']);
            }
            if (data.hasOwnProperty('defaults')) {
                obj['defaults'] = Defaults1.constructFromObject(data['defaults']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TemplateUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TemplateUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TemplateUpdateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['template_id'] && !(typeof data['template_id'] === 'string' || data['template_id'] instanceof String)) {
            throw new Error("Expected the field `template_id` to be a primitive type in the JSON string but got " + data['template_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['image_ref'] && !(typeof data['image_ref'] === 'string' || data['image_ref'] instanceof String)) {
            throw new Error("Expected the field `image_ref` to be a primitive type in the JSON string but got " + data['image_ref']);
        }
        // ensure the json data is a string
        if (data['template_str'] && !(typeof data['template_str'] === 'string' || data['template_str'] instanceof String)) {
            throw new Error("Expected the field `template_str` to be a primitive type in the JSON string but got " + data['template_str']);
        }
        // validate the optional field `fields`
        if (data['fields']) { // data not null
          Fields1.validateJSON(data['fields']);
        }
        // validate the optional field `defaults`
        if (data['defaults']) { // data not null
          Defaults1.validateJSON(data['defaults']);
        }

        return true;
    }


}

TemplateUpdateRequest.RequiredProperties = ["template_id"];

/**
 * @member {String} template_id
 */
TemplateUpdateRequest.prototype['template_id'] = undefined;

/**
 * @member {String} name
 */
TemplateUpdateRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
TemplateUpdateRequest.prototype['description'] = undefined;

/**
 * @member {String} image_ref
 */
TemplateUpdateRequest.prototype['image_ref'] = undefined;

/**
 * @member {String} template_str
 */
TemplateUpdateRequest.prototype['template_str'] = undefined;

/**
 * @member {module:model/Fields1} fields
 */
TemplateUpdateRequest.prototype['fields'] = undefined;

/**
 * @member {module:model/Defaults1} defaults
 */
TemplateUpdateRequest.prototype['defaults'] = undefined;






export default TemplateUpdateRequest;

