/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TemplateModel from './TemplateModel';

/**
 * The TemplateListResponse model module.
 * @module model/TemplateListResponse
 * @version 1.0.0
 */
class TemplateListResponse {
    /**
     * Constructs a new <code>TemplateListResponse</code>.
     *      List response for templates     
     * @alias module:model/TemplateListResponse
     * @param status {Number} 
     * @param message {String} 
     */
    constructor(status, message) { 
        
        TemplateListResponse.initialize(this, status, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, message) { 
        obj['status'] = status;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>TemplateListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateListResponse} obj Optional instance to populate.
     * @return {module:model/TemplateListResponse} The populated <code>TemplateListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateListResponse();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('total_templates')) {
                obj['total_templates'] = ApiClient.convertToType(data['total_templates'], 'Number');
            }
            if (data.hasOwnProperty('templates')) {
                obj['templates'] = ApiClient.convertToType(data['templates'], [TemplateModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TemplateListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TemplateListResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TemplateListResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['templates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['templates'])) {
                throw new Error("Expected the field `templates` to be an array in the JSON data but got " + data['templates']);
            }
            // validate the optional field `templates` (array)
            for (const item of data['templates']) {
                TemplateModel.validateJSON(item);
            };
        }

        return true;
    }


}

TemplateListResponse.RequiredProperties = ["status", "message"];

/**
 * @member {String} description
 * @default ''
 */
TemplateListResponse.prototype['description'] = '';

/**
 * @member {Number} status
 */
TemplateListResponse.prototype['status'] = undefined;

/**
 * @member {String} message
 */
TemplateListResponse.prototype['message'] = undefined;

/**
 * @member {Number} total_templates
 * @default 0
 */
TemplateListResponse.prototype['total_templates'] = 0;

/**
 * @member {Array.<module:model/TemplateModel>} templates
 */
TemplateListResponse.prototype['templates'] = undefined;






export default TemplateListResponse;

