/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Email from './Email';
import Quota from './Quota';

/**
 * The UserCreateRequest model module.
 * @module model/UserCreateRequest
 * @version 1.0.0
 */
class UserCreateRequest {
    /**
     * Constructs a new <code>UserCreateRequest</code>.
     *      Create request for users     
     * @alias module:model/UserCreateRequest
     * @param username {String} 
     * @param password {String} 
     * @param email {module:model/Email} 
     * @param role {String} 
     */
    constructor(username, password, email, role) { 
        
        UserCreateRequest.initialize(this, username, password, email, role);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password, email, role) { 
        obj['username'] = username;
        obj['password'] = password;
        obj['email'] = email;
        obj['role'] = role;
    }

    /**
     * Constructs a <code>UserCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCreateRequest} obj Optional instance to populate.
     * @return {module:model/UserCreateRequest} The populated <code>UserCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCreateRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = Email.constructFromObject(data['email']);
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = Quota.constructFromObject(data['quota']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserCreateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // validate the optional field `email`
        if (data['email']) { // data not null
          Email.validateJSON(data['email']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // validate the optional field `quota`
        if (data['quota']) { // data not null
          Quota.validateJSON(data['quota']);
        }

        return true;
    }


}

UserCreateRequest.RequiredProperties = ["username", "password", "email", "role"];

/**
 * @member {String} username
 */
UserCreateRequest.prototype['username'] = undefined;

/**
 * @member {String} password
 */
UserCreateRequest.prototype['password'] = undefined;

/**
 * @member {module:model/Email} email
 */
UserCreateRequest.prototype['email'] = undefined;

/**
 * @member {String} role
 */
UserCreateRequest.prototype['role'] = undefined;

/**
 * @member {module:model/Quota} quota
 */
UserCreateRequest.prototype['quota'] = undefined;






export default UserCreateRequest;

