/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UserStatusEnum.
* @enum {}
* @readonly
*/
export default class UserStatusEnum {
    
        /**
         * value: "active"
         * @const
         */
        "active" = "active";

    
        /**
         * value: "inactive"
         * @const
         */
        "inactive" = "inactive";

    

    /**
    * Returns a <code>UserStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UserStatusEnum} The enum <code>UserStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

