/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserCreateResponseUser from './UserCreateResponseUser';

/**
 * The UserUpdateResponse model module.
 * @module model/UserUpdateResponse
 * @version 1.0.0
 */
class UserUpdateResponse {
    /**
     * Constructs a new <code>UserUpdateResponse</code>.
     *      Update response for users, the same as get response     
     * @alias module:model/UserUpdateResponse
     * @param status {Number} 
     * @param message {String} 
     */
    constructor(status, message) { 
        
        UserUpdateResponse.initialize(this, status, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, message) { 
        obj['status'] = status;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>UserUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserUpdateResponse} obj Optional instance to populate.
     * @return {module:model/UserUpdateResponse} The populated <code>UserUpdateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserUpdateResponse();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = UserCreateResponseUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserUpdateResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserUpdateResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserUpdateResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          UserCreateResponseUser.validateJSON(data['user']);
        }

        return true;
    }


}

UserUpdateResponse.RequiredProperties = ["status", "message"];

/**
 * @member {String} description
 * @default ''
 */
UserUpdateResponse.prototype['description'] = '';

/**
 * @member {Number} status
 */
UserUpdateResponse.prototype['status'] = undefined;

/**
 * @member {String} message
 */
UserUpdateResponse.prototype['message'] = undefined;

/**
 * @member {module:model/UserCreateResponseUser} user
 */
UserUpdateResponse.prototype['user'] = undefined;






export default UserUpdateResponse;

