/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QuotaModel from './QuotaModel';
import ResourceStatusEnum from './ResourceStatusEnum';
import UserRoleEnum from './UserRoleEnum';
import UserStatusEnum from './UserStatusEnum';

/**
 * The UserModel model module.
 * @module model/UserModel
 * @version 1.0.0
 */
class UserModel {
    /**
     * Constructs a new <code>UserModel</code>.
     * User model, used to define user
     * @alias module:model/UserModel
     * @param email {String} 
     * @param ownedPodIds {Array.<String>} 
     * @param password {String} 
     * @param quota {module:model/QuotaModel} 
     * @param role {module:model/UserRoleEnum} 
     * @param uid {Number} 
     * @param username {String} 
     * @param uuid {String} 
     * @param version {String} 
     */
    constructor(email, ownedPodIds, password, quota, role, uid, username, uuid, version) { 
        
        UserModel.initialize(this, email, ownedPodIds, password, quota, role, uid, username, uuid, version);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, ownedPodIds, password, quota, role, uid, username, uuid, version) { 
        obj['email'] = email;
        obj['owned_pod_ids'] = ownedPodIds;
        obj['password'] = password;
        obj['quota'] = quota;
        obj['role'] = role;
        obj['uid'] = uid;
        obj['username'] = username;
        obj['uuid'] = uuid;
        obj['version'] = version;
    }

    /**
     * Constructs a <code>UserModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserModel} obj Optional instance to populate.
     * @return {module:model/UserModel} The populated <code>UserModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserModel();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('extra_info')) {
                obj['extra_info'] = ApiClient.convertToType(data['extra_info'], {'String': Object});
            }
            if (data.hasOwnProperty('htpasswd')) {
                obj['htpasswd'] = ApiClient.convertToType(data['htpasswd'], 'String');
            }
            if (data.hasOwnProperty('owned_pod_ids')) {
                obj['owned_pod_ids'] = ApiClient.convertToType(data['owned_pod_ids'], ['String']);
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = ApiClient.convertToType(data['quota'], QuotaModel);
            }
            if (data.hasOwnProperty('resource_status')) {
                obj['resource_status'] = ResourceStatusEnum.constructFromObject(data['resource_status']);
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = UserRoleEnum.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = UserStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserModel.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['htpasswd'] && !(typeof data['htpasswd'] === 'string' || data['htpasswd'] instanceof String)) {
            throw new Error("Expected the field `htpasswd` to be a primitive type in the JSON string but got " + data['htpasswd']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['owned_pod_ids'])) {
            throw new Error("Expected the field `owned_pod_ids` to be an array in the JSON data but got " + data['owned_pod_ids']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // validate the optional field `quota`
        if (data['quota']) { // data not null
          QuotaModel.validateJSON(data['quota']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }

        return true;
    }


}

UserModel.RequiredProperties = ["email", "owned_pod_ids", "password", "quota", "role", "uid", "username", "uuid", "version"];

/**
 * @member {String} email
 */
UserModel.prototype['email'] = undefined;

/**
 * @member {Object.<String, Object>} extra_info
 */
UserModel.prototype['extra_info'] = undefined;

/**
 * @member {String} htpasswd
 */
UserModel.prototype['htpasswd'] = undefined;

/**
 * @member {Array.<String>} owned_pod_ids
 */
UserModel.prototype['owned_pod_ids'] = undefined;

/**
 * @member {String} password
 */
UserModel.prototype['password'] = undefined;

/**
 * @member {module:model/QuotaModel} quota
 */
UserModel.prototype['quota'] = undefined;

/**
 * @member {module:model/ResourceStatusEnum} resource_status
 */
UserModel.prototype['resource_status'] = undefined;

/**
 * @member {module:model/UserRoleEnum} role
 */
UserModel.prototype['role'] = undefined;

/**
 * @member {module:model/UserStatusEnum} status
 */
UserModel.prototype['status'] = undefined;

/**
 * @member {Number} uid
 */
UserModel.prototype['uid'] = undefined;

/**
 * @member {String} username
 */
UserModel.prototype['username'] = undefined;

/**
 * @member {String} uuid
 */
UserModel.prototype['uuid'] = undefined;

/**
 * @member {String} version
 */
UserModel.prototype['version'] = undefined;






export default UserModel;

