/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.AdminUserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminUserApi', function() {
    describe('deleteadminUserAdminUserDelete', function() {
      it('should call deleteadminUserAdminUserDelete successfully', function(done) {
        //uncomment below and update the code to test deleteadminUserAdminUserDelete
        //instance.deleteadminUserAdminUserDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getadminUserAdminUserGet', function() {
      it('should call getadminUserAdminUserGet successfully', function(done) {
        //uncomment below and update the code to test getadminUserAdminUserGet
        //instance.getadminUserAdminUserGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getadminUserAdminUserList', function() {
      it('should call getadminUserAdminUserList successfully', function(done) {
        //uncomment below and update the code to test getadminUserAdminUserList
        //instance.getadminUserAdminUserList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postadminUserAdminUserCreate', function() {
      it('should call postadminUserAdminUserCreate successfully', function(done) {
        //uncomment below and update the code to test postadminUserAdminUserCreate
        //instance.postadminUserAdminUserCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putadminUserAdminUserUpdate', function() {
      it('should call putadminUserAdminUserUpdate successfully', function(done) {
        //uncomment below and update the code to test putadminUserAdminUserUpdate
        //instance.putadminUserAdminUserUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
