/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.AuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthApi', function() {
    describe('getauthBasic', function() {
      it('should call getauthBasic successfully', function(done) {
        //uncomment below and update the code to test getauthBasic
        //instance.getauthBasic(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getauthBasicUser', function() {
      it('should call getauthBasicUser successfully', function(done) {
        //uncomment below and update the code to test getauthBasicUser
        //instance.getauthBasicUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getauthTokenValidateUser', function() {
      it('should call getauthTokenValidateUser successfully', function(done) {
        //uncomment below and update the code to test getauthTokenValidateUser
        //instance.getauthTokenValidateUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postauthTokenLogin', function() {
      it('should call postauthTokenLogin successfully', function(done) {
        //uncomment below and update the code to test postauthTokenLogin
        //instance.postauthTokenLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postauthTokenRefresh', function() {
      it('should call postauthTokenRefresh successfully', function(done) {
        //uncomment below and update the code to test postauthTokenRefresh
        //instance.postauthTokenRefresh(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
