/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.TemplateModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateModel', function() {
    it('should create an instance of TemplateModel', function() {
      // uncomment below and update the code to test TemplateModel
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be.a(Api.TemplateModel);
    });

    it('should have the property resourceStatus (base name: "resource_status")', function() {
      // uncomment below and update the code to test the property resourceStatus
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property templateId (base name: "template_id")', function() {
      // uncomment below and update the code to test the property templateId
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property imageRef (base name: "image_ref")', function() {
      // uncomment below and update the code to test the property imageRef
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property templateStr (base name: "template_str")', function() {
      // uncomment below and update the code to test the property templateStr
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property fields (base name: "fields")', function() {
      // uncomment below and update the code to test the property fields
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

    it('should have the property defaults (base name: "defaults")', function() {
      // uncomment below and update the code to test the property defaults
      //var instance = new Api.TemplateModel();
      //expect(instance).to.be();
    });

  });

}));
