#!/usr/bin/env python3
"""
Patch an OpenAPI 3.1-style JSON spec generated by Sanic/Pydantic so that
the openapi-generator JavaScript client can generate clean, stub-free code.

Two transformations are applied:

1. anyOf nullable → OAS 3.0 nullable
   anyOf: [{type: X, ...props}, {type: null}]
     →  {type: X, ...props, nullable: true}
   anyOf: [{$ref: "..."}, {type: null}]
     →  {allOf: [{$ref: "..."}], nullable: true}
   (Only 2-variant anyOf where exactly one variant is {type: null}.)

2. Strip inline $defs blocks from every schema node.
   The backend duplicates full model definitions inside each response body
   via $defs. The JS generator picks these up and creates duplicate /
   stub model files. Since the $defs are never $ref-referenced they are
   safe to drop; the generator already has the real definitions in
   components/schemas.

Usage:
    python3 scripts/patch_openapi.py openapi.json               # in-place
    python3 scripts/patch_openapi.py openapi.json patched.json  # to a new file
"""

import json
import sys


def fix_node(obj):
    """Recursively apply both transformations to a parsed JSON object."""
    if isinstance(obj, list):
        return [fix_node(v) for v in obj]
    if not isinstance(obj, dict):
        return obj

    # --- transformation 1: anyOf nullable ---
    if "anyOf" in obj:
        any_of = obj["anyOf"]
        if isinstance(any_of, list) and len(any_of) == 2:
            null_items = [x for x in any_of if x == {"type": "null"}]
            non_null = [x for x in any_of if x != {"type": "null"}]
            if len(null_items) == 1 and len(non_null) == 1:
                rest = {k: v for k, v in obj.items() if k != "anyOf"}
                target = non_null[0]
                if "$ref" in target:
                    # Keep as allOf so the $ref stays intact (OAS 3.0 rule:
                    # nullable cannot be combined directly with $ref)
                    result = {"allOf": [target], "nullable": True}
                else:
                    result = dict(target)
                    result["nullable"] = True
                result.update(rest)
                obj = result

    # --- transformation 2: strip $defs ---
    obj = {k: v for k, v in obj.items() if k != "$defs"}

    # recurse after stripping so we don't descend into removed content
    return {k: fix_node(v) for k, v in obj.items()}


def patch(src_path, dst_path):
    with open(src_path, encoding="utf-8") as f:
        spec = json.load(f)

    patched = fix_node(spec)

    with open(dst_path, "w", encoding="utf-8") as f:
        json.dump(patched, f, indent=2)
        f.write("\n")

    # quick sanity check
    remaining_anyof = json.dumps(patched).count('"anyOf"')
    remaining_defs = json.dumps(patched).count('"$defs"')
    print(f"Patched {src_path} → {dst_path}")
    print(f"  anyOf occurrences remaining : {remaining_anyof}")
    print(f"  $defs occurrences remaining : {remaining_defs}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else src
    patch(src, dst)
